### ISSUE TITLE
Upgrade Yeast Name to smart-type with autofill

### ISSUE THREAD

**Issue by MichaelWashburnJr** [OpenBrews/OpenBrews#12]
Depends on #18 . Update the yeast name field to a smart-type field pulling yeast products from brewerydb. Autofill all possible fields based on the selection. Do not force users to select from this list, custom values are accepted.

**Comment by icyflame** [comment]
Hi, @mdw7326 .

Do you envision something like search and display as the user types in their query? using the API here: http://www.brewerydb.com/developers/docs-endpoint/yeast_index

(That API can return a list of all the yeasts or search using a particular ID. Query based search isn't available in that API.)

**Comment by MichaelWashburnJr** [comment]
@icyflame I didn't realize that the yeast endpoint didn't support searching. To implement this we will have to call `/yeasts` to get all yeasts (this is actually pretty fast), and then do our own search.

*I am also not sure what the best way to store a development API key is

I think the functionality should act as illustrated in the following use-case:
- The user clicks the yeast name field
- A dropdown list appears below with all possible yeasts, and their cursor is placed in the field for text to be entered
- The user enters one letter "A", and only yeast names starting with "A" are shown in the dropdown now

**Comment by icyflame** [comment]
Ah, got it. I have implemented stuff like this in native Android, but there was a search endpoint in the API then. Okay, if that particular request is really fast, then we can actually get all the 9-10 pages of results and take it from there. I will explore this further.

API key has me baffled too. They say "keep the API key private" but obviously in a web-application and in all open-source applications, the key would be public. Hmm, I will think about some kind of environment variable fix, but I don't think there are any for Ionic apps. Let's think of other ways to store the key, meanwhile.

**Comment by MichaelWashburnJr** [comment]
I think we could probably extract some configurations out into a config.json file, which is in the .gitignore. We would have to have a example-config.json committed to the repository. Then I would store the actual configs in gists and share them with developers when requested (alternatively, developers could sign up for their own API keys if they do not want to ask or if I fall into a black hole)

**Comment by MichaelWashburnJr** [comment]
#64 added services for this and #63 Has a smart type example using these services. This is now just applying those two things to this issue and should be straightforward.
