### ISSUE TITLE
Add Good Color Scheme

### ISSUE THREAD

**Issue by MichaelWashburnJr** [OpenBrews/OpenBrews#14]
Still using a blank white scheme, if someone wants to add some color to the scss, that'd be great.

**Comment by ankit01ojha** [comment]
Can you please tell me in which file of scss folder does the color option is?

**Comment by MichaelWashburnJr** [comment]
@ankit01ojha `openbrews/openbrews.app.scss` has default color options at the top that you can play around with. They are commented out, but if you uncomment them and start setting their values they should work.

**Comment by briantwatson** [comment]
@mdw7326, I'll take a stab at it.  I'll just use the colors eric used and apply them to the file you've described

**Comment by MichaelWashburnJr** [comment]
That works @briantwatson, thank you (referring to #50). I'm going to keep this issue open however in case someone wants to get creative. For example, if someone wants to add more creative colors for backgrounds, buttons, fonts, etc. It would be welcome still. Currently, the app looks a little generic still.

**Comment by briantwatson** [comment]
@mdw7326, sounds good.  New to Angular etc.  so I need to roll my sleeves up and see what I can do.  Was a homebrewer for some years, so this piqued my interest.

**Comment by icyflame** [comment]
@mdw7326 @briantwatson I am not too sure what changes were made in the color scheme. The app looks exactly the same to me, is there some step that I am missing? I am doing the same `gulp && ionic serve` or `gulp && ionic upload`. I don't see any change the overall color scheme!

**Comment by MichaelWashburnJr** [comment]
@icyflame They were very subtle changes, which is why I kept the issue open. One example is, I think the green buttons are slightly darker now.

**Comment by codeavenger07** [comment]
@mdw7326, mind if I take a stab at this?

**Comment by MichaelWashburnJr** [comment]
@codeavenger07 Go ahead!

**Comment by MichaelWashburnJr** [comment]
I think this is good enough for now
