### ISSUE TITLE
Add "others" section to "Add Recipe" form.

### ISSUE THREAD

**Issue by MichaelWashburnJr** [OpenBrews/OpenBrews#19]
The "others" section will be somewhere to add random ingredients used. See the Wiki for the recipe.others data format. Base the UI off the fermentables UI.

**Comment by hisk** [comment]
I will take care of this soon. :)

**Comment by MichaelWashburnJr** [comment]
@hiskie Great :) take a look at the fermentables section for some formatting guides

**Comment by MichaelWashburnJr** [comment]
Closed in #34
