### ISSUE TITLE
Add "notes" to "Add Recipe" form

### ISSUE THREAD

**Issue by MichaelWashburnJr** [OpenBrews/OpenBrews#20]
At the end of the form there should be a text field for a note and a button to add another note.

**Comment by wesleycsj** [comment]
Already exists a function to add a recipe, or a should create one?

**Comment by wesleycsj** [comment]
I can do it. Just a question, it needs a button to Add a note and another to remove each note?

**Comment by wesleycsj** [comment]
should be separate from functionality 'Add fermentable'?Why not use vm instead $scope in controllers?

**Comment by MichaelWashburnJr** [comment]
Yes, it should be seperate from "Add fermentable". And you caught me, and I really should be using a vm instead of scope

**Comment by wesleycsj** [comment]
I think that i can do it, but need to know a little more about the code.
