### ISSUE TITLE
When adding an ingredient on "Add Recipe", scroll view to bottom of page

### ISSUE THREAD

**Issue by MichaelWashburnJr** [OpenBrews/OpenBrews#25]
Currently, if you click "Add Fermentable" on the "Add Recipe" page, you have to manually scroll down to the newly added section. It would be more intuitive to scroll the new section into the view when it is added.

**Comment by icyflame** [comment]
> scroll view to bottom of page

Shouldn't this rather be: `scroll view to the top of the newly added section`. (since this is where the user is going to start typing text)

**Comment by MichaelWashburnJr** [comment]
Um, yes!

**Comment by icyflame** [comment]
@mdw7326 I think we can close this now. Now, when I run the app on the phone, it's a lot more stable, and doesn't jump around. This means whenever I add something, it's in the viewport, and can be reached quickly. I don't why but when we were using all that mock data the screen used to jump around weirdly.

Now, the app looks good in both Edit and Add Recipe.
