### ISSUE TITLE
Add Delete Recipe button in recipe list

### ISSUE THREAD

**Issue by MichaelWashburnJr** [OpenBrews/OpenBrews#26]
Make it so that if you slide the recipe to the right on Recipe List, a delete button appears on the left side of the row. When clicked, this should remove the recipe from local storage.

(Maybe the delete button should appear when you slide the recipe to the left? I'm not sure what the best ux practices are)

be sure to use both `ng-click` and `ng-tap` on the button.

**Comment by rishirajjain** [comment]
I'm interested in taking this up
