### ISSUE TITLE
Add Edit Recipe Functionality

### ISSUE THREAD

**Issue by MichaelWashburnJr** [OpenBrews/OpenBrews#27]
This should reuse the "Add Recipe" form. When you slide a recipe in the recipe list one direction, an edit button should appear. (See #26 for discussion on sliding direction)

**Comment by minibhati93** [comment]
Can I work on this issue?

**Comment by MichaelWashburnJr** [comment]
I do not think anyone is currently working on this. I think @icyflame expressed interest in this issue at one point but I believe he is not currently working on this.

**Comment by minibhati93** [comment]
Do you need the delete button in the list as well (as mentioned in this #26 discussion)?

**Comment by MichaelWashburnJr** [comment]
Yes, if you'd like to do both in one swoop then feel free 👍
