### ISSUE TITLE
Add Configuration Management

### ISSUE THREAD

**Issue by MichaelWashburnJr** [OpenBrews/OpenBrews#28]
We should make it so the main module (openbrews.js) reads in values from a config file (openbrews.config.json). We should not add the config file to the repository, but we should add an example config to the repository (something named like openbrews.config.ex.json). 

This is needed at minimum to store the brewerydb API key for the app. I will keep a concrete config in a gist and share it upon request with developers.

**Comment by lricoy** [comment]
I may be able to take a look at that issue and others one later today. Thanks for putting the Hacktoberfest label.

**Comment by admah** [comment]
I can take this one today if @lricoy can't get to it.
