### ISSUE TITLE
Recipe isn't added to list on main screen after saving it

### ISSUE THREAD

**Issue by icyflame** [OpenBrews/OpenBrews#30]
GIF attached:

![x-plqf](https://cloud.githubusercontent.com/assets/3668034/19160917/61c90362-8c0f-11e6-93bb-db1621c8e16a.gif)

I don't know what the right way to do this in Angular is. Do we need to bind an event, which needs to be emitted _after_ the recipe is saved to local storage?

**Comment by MichaelWashburnJr** [comment]
If we add `cache: false` to the `recipes` state in openbrews.js, I think it will fix the issue. I can't do it right now, but can get to it later if you don't want to

**Comment by minibhati93** [comment]
`$ionicView.beforeEnter` can also be used for loading the recipes before entering the state.
