### ISSUE TITLE
Hook up delete button in recipe list

### ISSUE THREAD

**Issue by MichaelWashburnJr** [OpenBrews/OpenBrews#36]
We need to make a function to delete the selected recipe from the list. There is a button stubbed out that can be viewed when you slide the list item to the left. We just need to write a function to delete the item from the database.

**Comment by MichaelWashburnJr** [comment]
@rmnblm is on this i think. For some reason I can't find him to put him as the assignee

**Comment by rmnblm** [comment]
Must be a bug. Maybe after writing this comment you have the ability to assign me.

**Comment by MichaelWashburnJr** [comment]
Closed in #43
