### ISSUE TITLE
Add "Edit Recipe" functionality and hook up button

### ISSUE THREAD

**Issue by MichaelWashburnJr** [OpenBrews/OpenBrews#37]
On the recipe list, there is a button to edit a recipe if you slide the list item to the left. We need to make a page to edit this recipe, using the same form as "Add Recipe", and then hook the existing edit button up.

**Comment by minibhati93** [comment]
Is anybody working on this issue currently? Can I try ?

**Comment by minibhati93** [comment]
I have a question regarding the UI. On clicking the edit button, should the selected recipe be opened in the existing "add recipe" form?

**Comment by MichaelWashburnJr** [comment]
Yes, It should be the same form, but we should probably fix anything that
says "Add Recipe" to "Edit Recipe" instead

**Comment by rmnblm** [comment]
@minibhati93 Yes, I'm currently working on this and #36

**Comment by MichaelWashburnJr** [comment]
Closed in #44
