### ISSUE TITLE
View Recipe

### ISSUE THREAD

**Issue by MichaelWashburnJr** [OpenBrews/OpenBrews#4]
Add a page to view a single recipe and all of its components.

**Comment by MichaelWashburnJr** [comment]
Here is the format for a recipe object:

```
{
  name: "Citra Pale Ale",
  style: "American Pale Ale",
  boilSize: 5,
  boilSizeUnits: "Gal",
  boilTime: 60,
  estFermTimeDays: 7,
  secondaryTimeDays: 7,
  mashEfficiency: 0.68,
  fermentables: [
    {
      name: "Pale Liquid Extract",
      method: "Extract",
      weight: 9.00,
      weightUnits: "Lbs",
      addTime: 15,
      ppg: 1.036,
      srm: 8.0
    }
  ],
  hops: [
    {
      name: "Citra",
      type: "Pellet",
      weight: 1,
      weightUnits: "OZ",
      aa: 0.125,
      stage: "Boil",
      addTime: 60
    },
    {
      name: "Citra",
      type: "Pellet",
      weight: 1,
      weightUnits: "OZ",
      aa: 0.125,
      stage: "Secondary"
    }
  ],
  yeast: [
    {
      name: "WY1056 American Ale",
      attenuation: 0.75,
      flocculation: "Medium-Low",
      amount: "13.5",
      amountUnits: "G"
    }
  ],
  others: [
    {
      name: "Orange Peel",
      amount: 5.0,
      amountUnits: "OZ",
      stage: "Boil"
      addTime: "60"
    },
    {
      name: "Orange Peel",
      amount: 5.0,
      amountUnits: "OZ",
      stage: "Secondary"
    }
  ],
  notes: [
    "Don't boil over!"
  ]
}
```

**Comment by cjwilburn** [comment]
Hey, I'd be happy to help on this project, especially since I'm also a homebrewer.

**Comment by MichaelWashburnJr** [comment]
Hi there @cjwilburn , thanks for getting in touch with me. You're help is certainly welcomed. If you're looking for a starting spot, I would suggest this issue. However, looking at it now this issue is still a bit loaded. I would suggest possibly starting with displaying the basic recipe data (everything not a list), and then moving on to the fermentables, yeast, hops, etc. I will try to update the readme in the meantime to be a little more descriptive of the project. Let me know if you need anything!

**Comment by atla5** [comment]
I'd consider controlling the vocabulary for "stage", "unit"s and/or flattening case. 

validation on all inputs would also do the trick, however, and this makes it easier for printing out.

**Comment by MichaelWashburnJr** [comment]
@atla5 Yes, this would definitely need heavy validation. `stage` would be either "Boil" or "Secondary". It could be represented as a boolean probably. I'd consider changing that to `inBoil`, so you know if the ingredient is added during the boil or in your secondary. I think "units" is necessary to account for metric/imperial and to keep. I do not see it being a value for any ingredient other than OZ, LBS, G, or KG though, so validation should definitely be done there as well..

**Comment by icyflame** [comment]
@mdw7326 Do you want to maintain similar UI as in the `Add Recipe` form? I believe that would make the most sense, and provide uniformity throughout the application.

**Comment by MichaelWashburnJr** [comment]
@icyflame I think it would make sense to stay uniform, but it is already kind of painful to scroll through that long list. Perhaps we could condense it by making each ingredient only take up 1 row (instead of having a card for each fermentable for example). We can emphasize important information such as the name and amount, and hide/make smaller all other information not needed to actually brew (like SRM/PPG on fermentable)

**Comment by icyflame** [comment]
@mdw7326 Indeed, that was exactly what I thought about. Scrolling on the computer is slightly painful, but on the phone, I think it will be just fine. And while viewing, one line per entry is fine. (I guess then can simply go into edit mode and change things when they want to, instead of us trying to merge the two modes into one. I will work on this tomorrow. :smile: Thanks for the clarification! )

**Comment by icyflame** [comment]
Most of the data binding work is done: https://github.com/icyflame/OpenBrews/tree/view-recipe

Only the UI part of this is remaining. :smile: It has been an interesting way to learn Ionic, Angular and the UI router. Will send a patch after completing this.
