### ISSUE TITLE
Create a better gitignore

### ISSUE THREAD

**Issue by icyflame** [OpenBrews/OpenBrews#40]
- Shouldn't include the CSS files which are generated by gulp
- Shouldn't include `.io-config.json` file which is generated by ionic on running `ionic upload`

**Comment by jllamasi** [comment]
I'll take care of that!

**Comment by icyflame** [comment]
@jllamasi Hey, I have already opened a PR ( #41 )

Thanks for your interest! Please have a look at the other issues on the dashboard :) Perhaps you could work on one of #37 / #38 / #36.

**Comment by minibhati93** [comment]
I have a question regarding the UI (Issue #37 ). On clicking the edit button, should the selected recipe be opened in the existing "add recipe" form?
