### ISSUE TITLE
Scrollbar doesn't "refresh" after adding/removing ingredients

### ISSUE THREAD

**Issue by rmnblm** [OpenBrews/OpenBrews#46]
When you add or remove an ingredient on the recipe page, the scrollbar doesn't refresh it's size.

**Steps to reproduce:**
1. Create a recipe with a few ingredients
2. Edit the recipe and remove all ingredients
3. Save the recipe and go back to all recipes
4. Edit the same recipe and add an ingredient
5. Now it's not possible to scroll down to the save button because the scroll bar didn't refresh

**Comment by MichaelWashburnJr** [comment]
This is somewhat related to #25 (but I think they're still two distinct issues)

**Comment by icyflame** [comment]
@rmnblm I just followed those steps on a browser, inside the lab, and it worked fine for me. The scrollbar automatically refreshes (I believe the container will do it as soon as new elements are added to the DOM)

@mdw7326 Did you face this issue in your testing?

**Comment by rmnblm** [comment]
I've made a gif which shows clearly what the problem is. If I have time today I'll fix it. 👍 

![video](https://cloud.githubusercontent.com/assets/5942764/19218398/406af518-8df9-11e6-8bb2-48ff6b3b9520.gif)

**Comment by icyflame** [comment]
@rmnblm Of course, scroll wheel doesn't work! Use your mouse to drag, as you would on a phone. That will work.

**Comment by MichaelWashburnJr** [comment]
@icyflame I'm considering reopening this issue. When testing on my phone, If I add fermentables and immediately scroll down, I cannot go all the way to the bottom of the page. If I wait a moment before trying to scroll, then it works correctly. Do you experience this?

**Comment by icyflame** [comment]
@mdw7326 I just tested the latest develop (81b43f1) branch on my phone, and it works well. There are no stutters like the ones you mention. I can scroll pretty much instantly.
