### ISSUE TITLE
Validation of a recipe: Don't let user add an empty recipe

### ISSUE THREAD

**Issue by icyflame** [OpenBrews/OpenBrews#51]
Right now, there's absolutely no validation. We can use HTML5 validation for specifying sane defaults for every field.

This might be slightly irritating when developing the application, but it will certainly be required in the stable release.

**Comment by JamesFranc** [comment]
@icyflame You're thinking a combination of required and pattern (regex) attributes on the field inputs, for [edit-recipe.html](https://github.com/OpenBrews/OpenBrews/blob/develop/openbrews/recipe/detail-edit/edit-recipe.html) yeah?

**Comment by icyflame** [comment]
@mdw7326 Maybe you should put together a list of the range of values for each field in the recipe. We could use that for the Validation service.

**Comment by MichaelWashburnJr** [comment]
@icyflame @JamesFranc take a look at the bottom of the first page of the wiki. Under the original recipe structure, I put validation rules for each field in a recipe
