### ISSUE TITLE
Change "Boiler Time" to "Boil Time" on View Recipe Page

### ISSUE THREAD

**Issue by MichaelWashburnJr** [OpenBrews/OpenBrews#54]

**Comment by JamesFranc** [comment]
I looked through the source and it appears as though this is already the case, or am I overlooking something?

https://github.com/OpenBrews/OpenBrews/blob/develop/openbrews/recipe/detail-readonly/view-recipe.html#L22

**Comment by icyflame** [comment]
@mdw7326 This is already fine :smile: Do you also want `Boiler size` to be changed to `Boil size`?

**Comment by icyflame** [comment]
@JamesFranc You are right. This wasn't an issue! Thanks for the time you spent looking through the code :slightly_smiling_face:

**Comment by MichaelWashburnJr** [comment]
Yes! Sorry, I meant Boiler Size should be Boil Size
