### ISSUE TITLE
Hide Notes section on View Recipe When empty

### ISSUE THREAD

**Issue by MichaelWashburnJr** [OpenBrews/OpenBrews#55]
The other sections are hidden on the ViewRecipe page if they are empty, the notes section should do the same.

**Comment by neelab** [comment]
I see the `AddRecipe` page but not `ViewRecipe`. Am I missing something?

**Comment by MichaelWashburnJr** [comment]
@neelab If you actually click on the list item, it should take you there.
If not, something may be wrong. Please post a screenshot if you keep having
trouble

**Comment by AhmedShab** [comment]
I'm on it

**Comment by AhmedShab** [comment]
I was testing it out to see what I have to solve. Added a recipe without notes but doesn't seems to be showing. Can you explain exatly what are you trying to do? Thanks :smile:

**Comment by icyflame** [comment]
Not an issue, I have already written code to ensure that this never happens:

``` js
  <h3 ng-if="recipe.notes.length > 0">Notes</h3>
```

https://github.com/OpenBrews/OpenBrews/blob/3e5ccf3d93af7ad62a3e610f436bb2d704481901/openbrews/recipe/detail-readonly/view-recipe.html#L106

**Comment by AhmedShab** [comment]
Awesome, nice work @icyflame :+1:
