### ISSUE TITLE
Calculate IBU and show on Edit/View Recipe Pages

### ISSUE THREAD

**Issue by MichaelWashburnJr** [OpenBrews/OpenBrews#61]
We should calculate the IBU of the brew based on it's ingredients. [This project](https://github.com/sbnedkov/trewbrews-calc/tree/master/src) has logic to do this and is open source. We should store this value on our recipe object, and make it editable in the Edit Recipe form. However, we should overwrite it with our calculation whenever the ingredients it uses in its calculation are modified.

Read [this](http://www.boxbrewkits.com/blogs/news/16337216-5-abbreviations-brewers-use-that-everyday-beer-drinkers-should-know) to find out more about IBU.

**Comment by maisieccino** [comment]
Sounds interesting, I'm going to give this a try :smile:

**Comment by maisieccino** [comment]
So, I'm thinking that the best way to approach this would be to create a RecipeUtils service, and use that service to provide some helper functions including this IBU calculation. And then this calculate function would be called from the EditRecipe controller.

**Comment by MichaelWashburnJr** [comment]
I like that idea @mbellgb. It should keep all the functionality separate and reusable. Also, be aware that the open source project I referenced is under the MIT license, so you can pretty much take whatever you need from that (if you wanted to)

**Comment by maisieccino** [comment]
@mdw7326, I've made a pull request with the first version of RecipeUtils. Let me know on that thread if anything needs changing! :slightly_smiling_face:

**Comment by MichaelWashburnJr** [comment]
See add-util-service branch
