### ISSUE TITLE
No validation is performed when saving a Recipe

### ISSUE THREAD

**Issue by savage-engineer** [OpenBrews/OpenBrews#62]
When creating or saving a Recipe the app does not appear to perform any validation on the fields. Of particular note - you can create a recipe with an empty string as it's name. Saving this then results in a blank button, which probably isn't an intended bit of functionality.

**Comment by MichaelWashburnJr** [comment]
This is the same as #51 I believe, correct?

**Comment by icyflame** [comment]
Closing this issue. This is a duplicate of #51. @savage-engineer Thanks for reporting! Please do search issues dashboard for the issue before creating a new one :slightly_smiling_face:

**Comment by savage-engineer** [comment]
Oops, missed that one!
