### ISSUE TITLE
Dropdown Menu's fight to be on top

### ISSUE THREAD

**Issue by MichaelWashburnJr** [OpenBrews/OpenBrews#65]
This issue is on branch  `add-smart-text`, in "edit-recipe.html", "fermentable.html", and "edit-recipe.scss"

I made the fermentable name a smart text field with a dropdown that searches for likely inputs. However, the beer style dropdown (above fermentables) is now going behind the fermentables field. It really looks like crap and can't stay. I'm not the best at HTML/CSS but have tried a few things and I'm not quite sure where to go next.

Any help would be appreciated, whether it be just suggestions or a PR.

**Comment by rustybailey** [comment]
So I wasn't able to fix this issue (it's definitely a z-index priority issue... just didn't have the time to look into it more deeply), but in setting up your app I was able to improve your docs: https://github.com/OpenBrews/OpenBrews/pull/66

**Comment by MichaelWashburnJr** [comment]
For some background: When I only had one dropdown, I set the z-index of the entire dropdown to 10 in edit-recipe.scss. Now, these two things with the same z-index are conflicting, and not showing in the right order.

**Comment by MichaelWashburnJr** [comment]
Closed in bb1f5eb
