### ISSUE TITLE
Installation to Android (5.1.1) Requires Altering Security Setting Change

### ISSUE THREAD

**Issue by atla5** [OpenBrews/OpenBrews#82]
Installing [OpenBrews apk 0.0.2](https://github.com/OpenBrews/OpenBrews/raw/develop/docs/releases/openbrews-0.0.2.apk) noto Android 5.1.1 requires editing the "Unknown Sources" setting to "Allow installation of apps from unknown sources". 

![Settings > Security > Device administration > Unknown Sources](https://cloud.githubusercontent.com/assets/5565284/20031810/dea71684-a353-11e6-98e7-f4e1dbc83e10.png)

**Comment by MichaelWashburnJr** [comment]
I added some documentation for this in  9c36fef. I figured the github pages site is the best place, because that's where people will download the binary from. I will also write this in the release notes when I tag it.

**Comment by icyflame** [comment]
@atla5 This is unavoidable. For all apps that need to be installed from an APK, this has to be done unfortunately.
